#!/bin/sh
# Compiles the nuclear integral scripts into local shared libraries.
# This is done automatically using setup.py in the main directory.

rm -f *.so
f2py -c --fcompiler=intelem -m nuclear_gaussian nuclear_gaussian.f90
f2py -c --fcompiler=intelem -m nuclear_dirac nuclear_dirac.f90
f2py -c --fcompiler=intelem -m nuclear_gaussian_ccs nuclear_gaussian_ccs.f90
